name: Build and Publish

on:
  push:
    branches:
      - main
    # accept tags that start with a digit (e.g. 1.2.3) — exclude tags that start with 'v'
    tags:
      - '[0-9]*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build

  publish:
    needs: build
    runs-on: ubuntu-latest
    # Only publish when a git tag is pushed
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js for publish
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Authenticate to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
      - name: Determine npm tag from git tag
        id: compute_tag
        shell: bash
        run: |
          # Use the git ref name provided by Actions
          TAG_NAME="${{ github.ref_name }}"
          echo "Git tag: $TAG_NAME"
          if [[ "$TAG_NAME" == *"-"* ]]; then
            # For tags like v1.2.3-beta.1 or v1.2.3-rc.1, extract the preid (beta, rc)
            PREID=$(echo "$TAG_NAME" | sed -E 's/^[^\-]*-([^\.]+).*/\1/')
            NPM_TAG="$PREID"
          else
            # For normal semver tags like v1.2.3 use 'latest'
            NPM_TAG=latest
          fi
          echo "npm_tag=$NPM_TAG" >> "$GITHUB_OUTPUT"
      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm publish --tag "${{ steps.compute_tag.outputs.npm_tag }}"
